// === core-js ===

"core-js/access.js"
"core-js/app.js"
"core-js/base.js"
"core-js/bootstrap.js"
"core-js/debug.js"
"core-js/events.js"
"core-js/filters.js"
"core-js/functions.js"
"core-js/init.js"
"core-js/io.js"
"core-js/lti.js"
"core-js/main.js"
"core-js/media.js"
"core-js/mediakron.js"
"core-js/models.js"
"core-js/router.js"
"core-js/state.js"

// core-js > Collections
"core-js/collections.js"
"core-js/collections/comments.js"
"core-js/collections/groups.js"
"core-js/collections/items.js"
"core-js/collections/search_results.js"
"core-js/collections/sites.js"
"core-js/collections/tags.js"
"core-js/collections/users.js"
"core-js/collections/zooms.js"

// core-js > Extensions
"core-js/extensions/collections.js"
"core-js/extensions/init.js"
"core-js/extensions/models.js"
"core-js/extensions/views.js"

// core-js > Models
"core-js/models/comment.js"
"core-js/models/group.js"
"core-js/models/item.js"
"core-js/models/site.js"
"core-js/models/user.js"

// core-js > Util
"core-js/util/class.management.js"

// core-js > Views
"core-js/views/controller.js"
"core-js/views/pages.js"
"core-js/views/popups.js"

// core-js > Vendor
"core-css/vendor/backbone/backbone-min.js"
"core-css/vendor/backbone/backbone.js"
"core-css/vendor/jquery-htmlclean/jquery.htmlClean.js"
"core-css/vendor/jquery-htmlclean/jquery.htmlClean.min.js"
"core-css/vendor/jquery/dist/jquery.js"
"core-css/vendor/jquery/dist/jquery.min.js"
"core-css/vendor/jquery/src/ajax.js"
"core-css/vendor/jquery/src/ajax/jsonp.js"
"core-css/vendor/jquery/src/ajax/load.js"
"core-css/vendor/jquery/src/ajax/parseJSON.js"
"core-css/vendor/jquery/src/ajax/parseXML.js"
"core-css/vendor/jquery/src/ajax/script.js"
"core-css/vendor/jquery/src/ajax/var/location.js"
"core-css/vendor/jquery/src/ajax/var/nonce.js"
"core-css/vendor/jquery/src/ajax/var/rquery.js"
"core-css/vendor/jquery/src/ajax/xhr.js"
"core-css/vendor/jquery/src/attributes.js"
"core-css/vendor/jquery/src/attributes/attr.js"
"core-css/vendor/jquery/src/attributes/classes.js"
"core-css/vendor/jquery/src/attributes/prop.js"
"core-css/vendor/jquery/src/attributes/support.js"
"core-css/vendor/jquery/src/attributes/val.js"
"core-css/vendor/jquery/src/callbacks.js"
"core-css/vendor/jquery/src/core.js"
"core-css/vendor/jquery/src/core/access.js"
"core-css/vendor/jquery/src/core/init.js"
"core-css/vendor/jquery/src/core/parseHTML.js"
"core-css/vendor/jquery/src/core/ready.js"
"core-css/vendor/jquery/src/core/support.js"
"core-css/vendor/jquery/src/core/var/rsingleTag.js"
"core-css/vendor/jquery/src/css.js"
"core-css/vendor/jquery/src/css/addGetHookIf.js"
"core-css/vendor/jquery/src/css/adjustCSS.js"
"core-css/vendor/jquery/src/css/curCSS.js"
"core-css/vendor/jquery/src/css/defaultDisplay.js"
"core-css/vendor/jquery/src/css/hiddenVisibleSelectors.js"
"core-css/vendor/jquery/src/css/showHide.js"
"core-css/vendor/jquery/src/css/support.js"
"core-css/vendor/jquery/src/css/var/cssExpand.js"
"core-css/vendor/jquery/src/css/var/getStyles.js"
"core-css/vendor/jquery/src/css/var/isHidden.js"
"core-css/vendor/jquery/src/css/var/rmargin.js"
"core-css/vendor/jquery/src/css/var/rnumnonpx.js"
"core-css/vendor/jquery/src/css/var/swap.js"
"core-css/vendor/jquery/src/data.js"
"core-css/vendor/jquery/src/data/accepts.js"
"core-css/vendor/jquery/src/data/Data.js"
"core-css/vendor/jquery/src/data/support.js"
"core-css/vendor/jquery/src/data/var/acceptData.js"
"core-css/vendor/jquery/src/data/var/dataPriv.js"
"core-css/vendor/jquery/src/data/var/dataUser.js"
"core-css/vendor/jquery/src/deferred.js"
"core-css/vendor/jquery/src/deprecated.js"
"core-css/vendor/jquery/src/dimensions.js"
"core-css/vendor/jquery/src/effects.js"
"core-css/vendor/jquery/src/effects/animatedSelector.js"
"core-css/vendor/jquery/src/effects/support.js"
"core-css/vendor/jquery/src/effects/Tween.js"
"core-css/vendor/jquery/src/event.js"
"core-css/vendor/jquery/src/event/ajax.js"
"core-css/vendor/jquery/src/event/alias.js"
"core-css/vendor/jquery/src/event/focusin.js"
"core-css/vendor/jquery/src/event/support.js"
"core-css/vendor/jquery/src/event/trigger.js"
"core-css/vendor/jquery/src/exports/amd.js"
"core-css/vendor/jquery/src/exports/global.js"
"core-css/vendor/jquery/src/intro.js"
"core-css/vendor/jquery/src/jquery.js"
"core-css/vendor/jquery/src/manipulation.js"
"core-css/vendor/jquery/src/manipulation/_evalUrl.js"
"core-css/vendor/jquery/src/manipulation/buildFragment.js"
"core-css/vendor/jquery/src/manipulation/createSafeFragment.js"
"core-css/vendor/jquery/src/manipulation/getAll.js"
"core-css/vendor/jquery/src/manipulation/setGlobalEval.js"
"core-css/vendor/jquery/src/manipulation/support.js"
"core-css/vendor/jquery/src/manipulation/var/nodeNames.js"
"core-css/vendor/jquery/src/manipulation/var/rcheckableType.js"
"core-css/vendor/jquery/src/manipulation/var/rleadingWhitespace.js"
"core-css/vendor/jquery/src/manipulation/var/rscriptType.js"
"core-css/vendor/jquery/src/manipulation/var/rtagName.js"
"core-css/vendor/jquery/src/manipulation/wrapMap.js"
"core-css/vendor/jquery/src/offset.js"
"core-css/vendor/jquery/src/outro.js"
"core-css/vendor/jquery/src/queue.js"
"core-css/vendor/jquery/src/queue/delay.js"
"core-css/vendor/jquery/src/selector-native.js"
"core-css/vendor/jquery/src/selector-sizzle.js"
"core-css/vendor/jquery/src/selector.js"
"core-css/vendor/jquery/src/serialize.js"
"core-css/vendor/jquery/src/support.js"
"core-css/vendor/jquery/src/traversing.js"
"core-css/vendor/jquery/src/traversing/findFilter.js"
"core-css/vendor/jquery/src/traversing/var/dir.js"
"core-css/vendor/jquery/src/traversing/var/rneedsContext.js"
"core-css/vendor/jquery/src/traversing/var/siblings.js"
"core-css/vendor/jquery/src/var/arr.js"
"core-css/vendor/jquery/src/var/class2type.js"
"core-css/vendor/jquery/src/var/concat.js"
"core-css/vendor/jquery/src/var/deletedIds.js"
"core-css/vendor/jquery/src/var/document.js"
"core-css/vendor/jquery/src/var/documentElement.js"
"core-css/vendor/jquery/src/var/hasOwn.js"
"core-css/vendor/jquery/src/var/indexOf.js"
"core-css/vendor/jquery/src/var/pnum.js"
"core-css/vendor/jquery/src/var/push.js"
"core-css/vendor/jquery/src/var/rcssNum.js"
"core-css/vendor/jquery/src/var/rnotwhite.js"
"core-css/vendor/jquery/src/var/slice.js"
"core-css/vendor/jquery/src/var/support.js"
"core-css/vendor/jquery/src/var/toString.js"
"core-css/vendor/jquery/src/wrap.js"
"core-css/vendor/rangy.main.js"
"core-css/vendor/requirejs/require.js"
"core-css/vendor/underscore/underscore-min.js"
"core-css/vendor/underscore/underscore.js"

// === Compontents ===

// Components > Content
"components/content/add-panes/addpane-general/addpane-general-view.js"

"components/content/browsers/browsers.js"

"components/content/comments/comments-page/comments-page-view.js"
"components/content/comments/comments-settings/comments-settings.js"
"components/content/comments/comments-story/comment-edit/comment-edit-view.js"
"components/content/comments/comments-story/comment-sidebar/comments-sidebar-view.js"
"components/content/comments/story-comments-edit/comment.js"
"components/content/comments/story-comments-page/comment-page-view.js"

"components/content/content-tools/copy-to-site/copy-to-site-view.js"
"components/content/content-tools/export/export-view.js"
"components/content/content-tools/import/import-view.js"
"components/content/content-tools/search/search-page/search-page-view.js"
"components/content/content-tools/search/search-settings/search-settings-view.js"
"components/content/content-tools/search/search-settings/settings.js"
"components/content/content-tools/trash/trash-view.js"

"components/content/item-edit/content-edit-view.js"
"components/content/item-edit/map-edit/map-marker-edit/map-marker-edit-view.js"
"components/content/item-edit/story-edit/story-add/features/features.js"
"components/content/item-edit/story-edit/story-edit-page/edit.js"
"components/content/item-edit/story-edit/story-edit-page/edit.v2.js"
"components/content/item-edit/story-edit/story-edit-page/editor.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/jquery.htmlclean.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/markdown.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/parse.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/paste.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/selection.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/storage.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/tracking.js"
"components/content/item-edit/story-edit/story-wysiwyg/wysiwyg/wysiwyg.js"
"components/content/item-edit/timeline-edit/timeline-edit-dates/format.js"
"components/content/item-edit/timeline-edit/timeline-edit-page/admin.js"

"components/content/item-elements/breadcrumbs/breadcrumb-view.js"
"components/content/item-elements/item-manager/manager-view.js"
"components/content/item-elements/item-page-options/item-page-options-view.js"
"components/content/item-elements/item-view-in/item-view-in-view.js"
"components/content/item-elements/map-timeline-filters/map-timeline-filters-view.js"
"components/content/item-elements/pdf-viewer/build/components/compatibility.js"
"components/content/item-elements/pdf-viewer/build/components/pdf_viewer.js"
"components/content/item-elements/pdf-viewer/build/generic/build/pdf.js"
"components/content/item-elements/pdf-viewer/build/generic/build/pdf.worker.js"
"components/content/item-elements/pdf-viewer/build/generic/web/compatibility.js"
"components/content/item-elements/pdf-viewer/build/generic/web/debugger.js"
"components/content/item-elements/pdf-viewer/build/generic/web/l10n.js"
"components/content/item-elements/pdf-viewer/build/generic/web/viewer.js"
"components/content/item-elements/pdf-viewer/build/pdf.js"
"components/content/item-elements/pdf-viewer/build/pdf.worker.js"
"components/content/item-elements/pdf-viewer/pdfjs/components/compatibility.js"
"components/content/item-elements/pdf-viewer/pdfjs/components/pdf_viewer.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/build/pdf.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/build/pdf.worker.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/web/compatibility.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/web/debugger.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/web/l10n.js"
"components/content/item-elements/pdf-viewer/pdfjs/generic/web/viewer.js"
"components/content/item-elements/pdf-viewer/pdfjs/pdf.js"
"components/content/item-elements/pdf-viewer/pdfjs/pdf.worker.js"
"components/content/item-elements/pdf-viewer/preview.js"
"components/content/item-elements/revisions/revisions-view.js"

"components/content/item-settings/item-options-view.js"

"components/content/select-panes/selector-canvas/selector-canvas-view.js"
"components/content/select-panes/selector-canvas/selector-canvas-row.js"

"components/content/item-types/audio/audio-view.js"
"components/content/item-types/comparison/comparison-view.js"
"components/content/item-types/file/file-view.js"
"components/content/item-types/folder/folder-view.js"
"components/content/item-types/image/image-annotation.js"
"components/content/item-types/image/image-view.js"
"components/content/item-types/map/map-view.js"
"components/content/item-types/map/maps.js"
"components/content/item-types/narrative/narrative-view.js"
"components/content/item-types/progression/progression-view.js"
"components/content/item-types/progression/progression.js"
"components/content/item-types/slideshow/slideshow-views.js"
"components/content/item-types/story/story-view.js"
"components/content/item-types/text/text-view.js"
"components/content/item-types/timeline/timeline-plugin/timeline.js"
"components/content/item-types/timeline/timeline-plugin/zoom.js"
"components/content/item-types/timeline/timeline-styles.js"
"components/content/item-types/video/video-view.js"

"components/content/organize-panes/comparison-organize/manage-comparison-view.js"
"components/content/organize-panes/map-organize/manage-map-view.js"
"components/content/organize-panes/narrative-organize/manage-narrative-view.js"
"components/content/organize-panes/organizer-view.js"
"components/content/organize-panes/progression-organize/manage-progression-view.js"
"components/content/organize-panes/slideshow-organize/manage-slideshow-view.js"
"components/content/organize-panes/timeline-organize/manage-timeline-view.js"

"components/content/tags/tag-page/tag-view.js"

// Components > Forms
"components/forms/edit.js"
"components/forms/form-expand-collapse/accessible-expand-plugin.js"

// Components > Help
"components/help/help-view.js"

// Components > Homepage
"components/homepage/homepage-settings/homepage-settings-view.js"
"components/homepage/homepage-view/homepage-view.js"
"components/homepage/homepage-view/welcome.js"

// Components > Settings
"components/settings/google-analytics/google-analytics-view.js"
"components/settings/privacy/privacy-view.js"
"components/settings/settings-page/settings-view.js"
"components/settings/site-cache/site-cache-view.js"
"components/settings/site-info/site-info-view.js"

// Components > Theme
"components/theme/navigation/accessible-nav/accessible-nav-plugin.js"
"components/theme/navigation/main-menu/main-menu.js"
"components/theme/navigation/menu-settings/menu-settings-view.js"
"components/theme/navigation/secondary-menu/secondary-menu.js"
"components/theme/site-appearance/site-appearance-view.js"

// Components > UI
"components/ui/fullscreen/fullscreen.js"

// Components > Users
"components/users/manage-users/manage-users-view.js"
"components/users/user-stats/user-stats-view.js"

// Components > Utiliies
"components/utilities/active-editors/active-editors-view.js"
"components/utilities/canvas/canvas-settings/canvas.js"
"components/utilities/error-page/error-page-view.js"
"components/utilities/login/login-view.js"
"components/utilities/messages/messages-view.js"
