nginx:
    build: ./docker/nginx/
    ports:
        - 81:80
        - 444:443
    links:
        - php
    volumes_from:
        - app

php:
    build: ./docker/php/
    expose:
        - 9000
    environment:
        DB_HOST: db
        DB_NAME: ${DB_DATABASE}
        DB_USER: ${DB_USERNAME}
        DB_PASS: ${DB_PASSWORD}
        PHP_ENV: ${APP_ENV}
    links:
        - db
    volumes_from:
        - app

app:
    image: php:7.2-fpm
    volumes:
        - ./public:/var/www/public
        - ./:/app
    command: "true"

db:
    image: mysql:5.6
    ports:
        - 3306:3306
    volumes:
        - ./db:/docker-entrypoint-initdb.d
        - ./db:/db-imports
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}

data:
    image: mysql:5.6
    volumes:
        - ./docker/data:/var/lib/mysql
    command: "true"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - db
    environment:
        PMA_HOST: db
