security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"

security_autoupdate_enabled: true
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "03:00"

security_autoupdate_mail_to: "ops@mediakron.us"
security_autoupdate_mail_on_error: true

security_fail2ban_enabled: true