all:
  hosts:
    ec2-52-90-188-176.compute-1.amazonaws.com:
      url: dev.api.mediakron.us
      env: development 
  children:
    dev:
      hosts:
        ec2-52-90-188-176.compute-1.amazonaws.com