export default SiteModel = {
    "id": Integer,
    "creator_id": Integer,
    "administrator_id": Integer,
    "institution_id": Integer,
    "comment": Integer,
    "download": Integer,
    "author": null,
    "view": 0,
    "public": 0,
    "initialized": 0,
    "production": 0,
    "indexed": 0,
    "sso": 0,
    "uri": String,
    "title": "Release 3.3",
    "subtitle": "Release 3.3",
    "logo": null,
    "ga": null,
    "algorithm": null,
    "navigation_color": null,
    "link_color": null,
    "banner_color": null,
    "banner_link_color": null,
    "skin": "default.css",
    "font": null,
    "item_id": 0,
    "item_uri": null,
    "description": null,
    "layout": null,
    "image": null,
    "alt": null,
    "navigation": "default",
    "browse": 0,
    "tags": 0,
    "search": 0,
    "mklogo": 0,
    "login": 0,
    "user": 0,
    "fullscreen": 0,
    "deleted_at": null,
    "created_at": "2015-11-06 01:11:22",
    "updated_at": "2018-12-09 22:21:42",
    "data": {
        "settings": "http://localhost/api/release_33"
    }
}